SamsungBasvuruProject.WebApi/Controllers/SamsungController.cs
using SamsungBasvuruProject.Business;
using SamsungBasvuruProject.Data;
using SamsungBasvuruProject.Data.TableClasses;
using SamsungBasvuruProject.WebApi;
using SamsungBasvuruProject.WebApi.FormDatas;
using SamsungBasvuruProject.WebApi.Filters;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Net.Http;
using System.Net.Http.Headers;

namespace SamsungBasvuruProject.Controllers
{
    public class SamsungController : AsyncController
    {
        Repository<User> _userRepository = new Repository<User>();
        Repository<Application> _applicationRepository = new Repository<Application>();

        public ActionResult Compare()
        {
            return View();
        }

        public ActionResult Login() // ÖNEMLİ:session ekle metodu sil!!!!!!!!!
        {
            return View(new User());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(User _user)
        {
            if (ModelState.IsValid)
            {
                var _checkValue = await checkAccount(_user);
                if (_checkValue)
                {
                    Session["User"] = _user;

                    FormsAuthentication.SetAuthCookie(_user.Username, false);

                    return RedirectToAction("ListApplications");
                }
                else
                {
                    @ViewBag.Message = "Kullanıcı Adı veya Şifrenizi tekrar kontrol ediniz!";
                    @ViewBag.Status = "danger";
                    return View();
                }
            }
            else
                return View();
        }

        public async Task<bool> checkAccount(User _user)
        {
            var _userCheck = await _userRepository.SingleGetBy(B => B.Username == _user.Username);


            if (_userCheck != null)
            {
                HashSaltClass hsc = new HashSaltClass();
                var _saltValue = _user.PasswordSalt;

                return await hsc.CheckPassword(_user.Username, _user.Password);
            }
            else
                return false;
        }

        [ActFilter, ResFilter, AuthFilter]
        public async Task<ActionResult> ListApplications()
        {
            List<ApplicationImageFormData> _appFormDataList = new List<ApplicationImageFormData>();
            //ImageByteOperations _ibo = new ImageByteOperations();
            var _applicationRepositories = await _applicationRepository.GetAll();

            foreach (var _appItem in _applicationRepositories.ToList())
            {
                ApplicationImageFormData _appFormData = new ApplicationImageFormData();
                _appFormData.Application = _appItem;
                _appFormData.Image = "data:image/png;base64," + Convert.ToBase64String(_appItem.Image);
                CheckApproveTypes(ref _appFormData);

                _appFormDataList.Add(_appFormData);
            }
            int ApprovedCount = _appFormDataList.Where(w => w.ApproveType == "Onaylanmış").Count();
            int UnApprovedCount = _appFormDataList.Where(w => w.ApproveType == "Henüz onaylanmamış").Count();
            int DeniedCount = _appFormDataList.Where(w => w.ApproveType == "Reddedilmiş").Count();

            @ViewBag.ApprovedCount = ApprovedCount;
            @ViewBag.UnApproved = UnApprovedCount;
            @ViewBag.DeniedCount = DeniedCount;

            return View(_appFormDataList.ToList());
        }


        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();


            return RedirectToAction("Login");
        }

        public void CheckApproveTypes(ref ApplicationImageFormData _appImageForm)
        {
            if (_appImageForm.Application.IsRejected == false && _appImageForm.Application.IsApproved == false)
            {
                _appImageForm.ApproveType = "Henüz onaylanmamış";
            }
            if (_appImageForm.Application.IsRejected == true && _appImageForm.Application.IsApproved == false)
            {
                _appImageForm.ApproveType = "Reddedilmiş";
            }
            if (_appImageForm.Application.IsRejected == false && _appImageForm.Application.IsApproved == true)
            {
                _appImageForm.ApproveType = "Onaylanmış";
            }

        }

        public ActionResult ReturnImage(byte[] imageData)
        {
            return new FileStreamResult(new System.IO.MemoryStream(imageData), "image/jpeg");
        }

        public async Task<ActionResult> ApplicationDetails(Guid ID)
        {
            var _application = await _applicationRepository.SingleGetBy(b => b.ID == ID);
            ApplicationImageFormData _appFormData = new ApplicationImageFormData();
            _appFormData.Application = _application;
            _appFormData.Image = "data:image/png;base64," + Convert.ToBase64String(_application.Image);
            @ViewBag.Username = _appFormData.Application.NameSurname + "'in Başvurusu";

            return View(_appFormData);
        }

        [HttpPost]
        public async Task<JsonResult> AcceptApplication(string _IMEINumber, string _isApproved, string _cityName, string _type)
        {
            var _approvedApplication = await _applicationRepository.SingleGetBy(b => b.IMEINumber == _IMEINumber);

            if (_type == "Accept")
            {
                _approvedApplication.IsApproved = true;
            }
            else
            {
                _approvedApplication.IsApproved = bool.Parse(_isApproved);
            }


            if (_cityName != null)
            {
                _approvedApplication.City = _cityName;
            }

            string Status;
            string Message;
            try
            {
                await _applicationRepository.Save();
                if (_type == "Accept")
                {
                    Status = "success";
                    Message = "Başvuru başarıyla onaylandı!";
                }
                else
                {
                    Status = "success";
                    Message = "Güncelleme başarıyla yapıldı!";
                }
            }
            catch (Exception ex)
            {
                if (_type == "Accept")
                {
                    Status = "danger";
                    Message = "Başvuru sırasında bir hata oluştu!";
                }
                else
                {
                    Status = "danger";
                    Message = "Güncelleme sırasında bir hata oluştu!";
                }
            }

            List<string> list = new List<string>();
            list.Add(Status);
            list.Add(Message);
            return Json(list);
        }

        [HttpPost]
        public async Task<JsonResult> DenyApplication(string _IMEINumber)
        {
            var _deniedApplication = await _applicationRepository.SingleGetBy(b => b.IMEINumber == _IMEINumber);
            _deniedApplication.IsApproved = false;
            _deniedApplication.IsRejected = true;

            string Status;
            string Message;
            try
            {
                await _applicationRepository.Save();

                Status = "success";
                Message = "Başvuru başarıyla reddedildi!";
            }
            catch (Exception ex)
            {
                Status = "danger";
                Message = "Başvuru reddetme sırasında bir hata oluştu!";
            }

            List<string> list = new List<string>();
            list.Add(Status);
            list.Add(Message);
            return Json(list);
        }

        public ActionResult CreateAccount()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CreateAccount(User _user)
        {
            HashSaltClass hsc = new HashSaltClass();

            User _newUser = new User();
            
            _newUser.Username = _user.Username;
            _newUser.PasswordSalt = hsc.GetSalt();
            _newUser.Password = hsc.GetHashSaltPassword(_user.Password, _newUser.PasswordSalt);

            await _userRepository.Add(_newUser);

            int _saveResult = 0;
            try
            {
                _saveResult = await _userRepository.Save();
                if (_saveResult > 0)
                {
                    @ViewBag.Status = "success";
                    @ViewBag.Message = "Kullanıcı başarıyla eklendi!";
                }
                else
                {
                    @ViewBag.Status = "info";
                    @ViewBag.Message = "Hiç bir kayıt değişmedi!";
                }


            }
            catch (Exception ex)
            {
                @ViewBag.Status = "danger";

                var _innerEx = ex.InnerException;
                Exception _tempInnerEx = _innerEx;

                if (_tempInnerEx != null)
                {
                    while (_tempInnerEx != null)
                    {
                        _tempInnerEx = _innerEx.InnerException;

                        if (_tempInnerEx == null)
                        {
                            @ViewBag.Message = _innerEx.Message;
                        }
                        _innerEx = _innerEx.InnerException;
                    }
                }

            }
            return View();
        }

        public ActionResult CreateApplication()
        {
            return View(new SamsungBasvuruProject.Data.TableClasses.Application());
        }


    }
}

SamsungBasvuruProject.WebApi/Views/Samsung/ApplicationDetails.cshtml
@model SamsungBasvuruProject.WebApi.FormDatas.ApplicationImageFormData

@{
    ViewBag.Title = @ViewBag.Username;
}


@*<link href="~/Content/ImageStyle.css" rel="stylesheet" />*@
<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.0.min.js"></script>
<script src="~/Content/ImageFullScreen.js"></script>

<script type="text/javascript">

    $(function () {
        $('#imageArea').click(function () {
            togglePhoto();
        });

        $('#btnAccept').click(function () {

            var _city = $('#Application_City').val();
            $.post("../../Samsung/AcceptApplication?_IMEINumber=" +@Model.Application.IMEINumber +"&_isApproved=" + "@Model.Application.IsApproved.ToString()" + "&_cityName=" + _city + "&_type=Accept")
                .success(function (veri) {
                    var status = veri[0];
                    var message = veri[1];

                    $('#alertArea').attr('class', 'alert alert-' + status);
                    $('#alertArea').text(message);

                });

        });

        $('#btnEdit').click(function () {
            var _city = $('#Application_City').val();
            $.post("../../Samsung/AcceptApplication?_IMEINumber=" +@Model.Application.IMEINumber +"&_isApproved=" + "@Model.Application.IsApproved.ToString()" + "&_cityName=" + _city + "&_type=Edit")
                .success(function (veri) {
                    var status = veri[0];
                    var message = veri[1];

                    $('#alertArea').attr('class', 'alert alert-' + status);
                    $('#alertArea').text(message);

                });
        });

        $('#btnDeny').click(function () {
            var _imeiNumber = $('#imeiArea').val();
            $.post("../../Samsung/DenyApplication?_IMEINumber=" + @Model.Application.IMEINumber+"")
                .success(function (veri) {
                    var status = veri[0];
                    var message = veri[1];

                    $('#alertArea').attr('class', 'alert alert-' + status);
                    $('#alertArea').text(message);
                });
        });

        function togglePhoto() {
            if ($('#imageArea').attr('width') == "100%") {
                $('#imageArea').attr('width', "25%");
                $('#imageArea').attr('height', "25%");
            }
            else {
                $('#imageArea').attr('width', "100%");
                $('#imageArea').attr('height', "100%");
            }
        };

    });

</script>


<h2>@ViewBag.Username</h2>


<div>
    <h4>Başvuru</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Application.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Application.Name)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.Application.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Application.Surname)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.Application.MobileNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Application.MobileNumber)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.Application.IMEINumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Application.IMEINumber, new { id="imeiArea"})
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.Application.Image)
        </dt>

        <dd>
            @*<div class="demo-image" data-image="@Url.Action("ReturnImage", "Samsung", new { imageData=@Model.Application.Image})" data-title="Başvuru" data-caption="@Model.Application.NameSurname" id="imageArea"></div>*@
            <img src="@Model.Image" width="25%" height="25%" alt="" id="imageArea" />
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.Application.City)
        </dt>

        <dd>
            @Html.EditorFor(model => model.Application.City)
            @Html.ValidationMessageFor(model => model.Application.City)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.Application.IsApproved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Application.IsApproved)
        </dd>
    </dl>
</div>

<p>
    <button type="button" class="btn btn-danger" id="btnDeny">Reddet</button> &nbsp;
    <button type="button" class="btn btn-default" id="btnEdit">Güncelle</button>&nbsp;
    <button type="button" class="btn btn-success" id="btnAccept">Onayla</button>
</p>
<p>
    @Html.ActionLink("Listeye Geri Dön", "ListApplications")
</p>
<div class="alert alert-@ViewBag.Status" role="alert" id="alertArea">@ViewBag.Message</div>

SamsungBasvuruProject.WebApi/Views/Samsung/Compare.cshtml
@{
    ViewBag.Title = "Compare";
}

<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.0.min.js"></script>
<script type="text/javascript">



    $(document).ready(function () {
        $('#btnCompare').click(function () {
            var _imei = $('#imeiTxt').val();
            $.getJSON('../api/SamsungApi/CompareVals/GetString?_imei=' + _imei).done(function (veri) {
                alert(veri);
            }).error(function (xhr, options, error) {
                if (error == "Not Found")
                    alert('IMEI Numarası bulunamadı.');
            });
        });

        $('#btnByteArray').click(function () {
            var _values = $('#byteArrayText').val();
            $.getJSON('../api/SamsungApi/DatabaseToImage').success(function (veri) {
                //veri.src = "data:image/jpg;base64," + veri.d;
                //var w = window.open("");
                //w.document.write(veri.outerHTML);
                window.open(veri, "_blank");
            })

        });

        $('#btnSalt').click(function () {
            var pwd = $('#saltText').val();
            $.getJSON('../api/SamsungApi/Tuzla?_password=' + pwd).done(function (veri) {
                alert(veri);

            });
        });

        $('#btnPwd').click(function () {
            var _usernameVal = $('#usernameText').val();
            var _passwordVal = $('#passwordText').val();

            $.getJSON('../api/SamsungApi/ComparePasswords?_username=' + _usernameVal + '&_password=' + _passwordVal).done(function (veri) {
                alert(veri);

            }).error(function (xhr, options, error) {
                if (error == "Not Found") {
                    alert('Şifreler uyuşmamaktadır');
                }
            });
        });


        function getBase64Image(img) {

            var canvas = document.createElement("canvas");
            canvas.width = img.width;
            canvas.height = img.height;

            var ctx = canvas.getContext("2d");
            ctx.drawImage(img, 0, 0);

            var dataURL = canvas.toDataURL("image/png");

            return dataURL.replace(/^data:image\/(png|jpg);base64,/, "");
        }

        var handleFileSelect = function (evt) {
            var files = evt.target.files;
            var file = files[0];

            if (files && file) {
                var reader = new FileReader();

                reader.onload = function (readerEvt) {
                    var binaryString = readerEvt.target.result;
                    document.getElementById("base64textarea").value = btoa(binaryString);
                };

                reader.readAsBinaryString(file);
            }
        };

        if (window.File && window.FileReader && window.FileList && window.Blob) {
            document.getElementById('imageFile').addEventListener('change', handleFileSelect, false);
        } else {
            alert('The File APIs are not fully supported in this browser.');
        }

        $('#btnImage').click(function () {

            //$.getJSON('../api/SamsungApi/ImageToDatabase?_image=' + $('#base64textarea').val()).success(function (veri) {
            //    alert(veri);

            var _parameter = $('#base64textarea').val();

            $.ajax({
                type: "GET",
                url: "/api/SamsungApi/ImageToDatabase",
                async:false,
                data: {_image:JSON.stringify(_parameter)},
                contentType: 'application/json; charset=utf-8',
                dataType:'json',
                success: function (response) {
                    alert(response.status);
                },
                error: function () {
                    alert("error");
                }
            });

        });
    });

</script>


<h2>Compare</h2>

IMEI KONTROL
<input type="text" id="imeiTxt" />
<input type="button" id="btnCompare" value="Check" />
<br />
ŞİFRE SALT HASH
<input type="text" id="saltText" value="password" />
<input type="button" id="btnSalt" value="Şifre Oluştur" />
<br />
PASSWORD KONTROL //TAM TAMAMLANMADI
<input type="text" id="usernameText" value="Kullanıcı Adı" />
<input type="text" id="passwordText" />
<input type="button" id="btnPwd" value="Şifreleri Karşılaştır" />
<br />


    IMAGE İŞLEMLERİ
<input type="file" id="imageFile" />
<br />
<div id="imageArea"></div>
<input type="button" id="btnImage" value="Image to Byte Array Button" />
<input type="button" id="btnByteArray" value="Byte Array to Image Button" />


<input type="hidden" id="base64textarea" />
<hr />
<br />
<img src="~/ImageFolder/riptide.jpg" id="image" />
<br />
<br />
<br />

SamsungBasvuruProject.WebApi/Views/Samsung/CreateAccount.cshtml
@model SamsungBasvuruProject.Data.User

@{
    ViewBag.Title = "CreateAccount";
}

<h2>CreateAccount</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    <div class="alert alert-@ViewBag.Status" role="alert">@ViewBag.Message</div>
}

    

SamsungBasvuruProject.WebApi/Views/Samsung/ListApplications.cshtml
@model IEnumerable<SamsungBasvuruProject.WebApi.FormDatas.ApplicationImageFormData>

    @{
    ViewBag.Title = "BAŞVURULARI LİSTELE";
    }
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <h2>BAŞVURULARI LİSTELE</h2>

    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.0.min.js"></script>
    <script type="text/javascript">
    $(function () {
        var input, filter, table, tr, td, i, j, counter;
        var filterCounter = 1;

        //counter = 0;
        $('#filterChoose').html("İsim <span class=\"caret\"></span>");

        var chooseInput = $('.dropdown-menu').children();

        for (i = 0; i < chooseInput.length; i++) {
            var childInputs = chooseInput.eq(i).children();

            childInputs.click(function () {
                $('#filterChoose').html($(this).html() + " <span class=\"caret\"></span>");
                var filter = $('#filterChoose').html();
                if (filter == "İsim <span class=\"caret\"></span>") {
                    filterCounter = 1;
                }
                if (filter == "Soyisim <span class=\"caret\"></span>") {
                    filterCounter = 2;
                }
                if (filter == "Telefon Numarası <span class=\"caret\"></span>") {
                    filterCounter = 3;
                }
                if (filter == "IMEINumber <span class=\"caret\"></span>") {
                    filterCounter = 4;
                }
                if (filter == "Şehir <span class=\"caret\"></span>") {
                    filterCounter = 6;
                }
            });
        }

        var infoChildren = $('#info').children(); //info tablosu içi tr->th
        var successChildren = $('#success').children(); //info tablosu içi tr->th
        var dangerChildren = $('#danger').children(); //info tablosu içi tr->th
        $('#filterArea').keyup(function (event) {
            input = $("#filterArea").val();
            filter = input.toUpperCase();
            table = $("table");
            for (j = 0; j < table.length; j++) {
                tr = table[j].getElementsByTagName("tr");
                var counterBadge = 0;
                for (i = 0; i < tr.length; i++) {
                    td = tr[i].getElementsByTagName("td")[filterCounter];
                    if (td) {
                        if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                            tr[i].style.display = "";
                            counterBadge++;
                            counter++;
                        } else {
                            tr[i].style.display = "none";
                        }}}
                if (j == 0) { //info badge ına yaz
                    if (counterBadge < 0) {
                        counterBadge = 0;
                    }
                    $('#UnapprovedBadge').html(counterBadge);
                    $('#info-badge').html(counterBadge);
                }
                if (j == 1) { //success badge ına yaz
                    if (counterBadge < 0) {
                        counterBadge = 0;}
                    $('#ApprovedBadge').html(counterBadge);
                    $('#success-badge').html(counterBadge);}
                if (j == 2) { //danger badge ına yaz
                    if (counterBadge < 0) {
                        counterBadge = 0;
                    }
                    $('#DeniedBadge').html(counterBadge);
                    $('#danger-badge').html(counterBadge);
                }}
        });
    });
    </script>

    <div class="panel panel-default">
        <div class="panel-heading">BAŞVURU TÜRLERİ</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-3 align-self-start" style="width:300px">
                    <button type="button" class="btn btn-info"><span class="glyphicon glyphicon-warning-sign"></span><a href="#Henüz onaylanmamış" style="color:white"> Henüz Onaylanmamış Başvurular</a>&nbsp<span class="badge" id="UnapprovedBadge">  @ViewBag.UnApproved</span></button>
                </div>
                <div class="col-xs-3" style="width:250px">
                    <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span><a href="#Onaylanmış" style="color:white"> Onaylanmış Başvurular</a>&nbsp<span class="badge" id="ApprovedBadge">  @ViewBag.ApprovedCount</span></button>
                </div>
                <div class="col-xs-3" style="width:250px">
                    <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span><a href="#Reddedilmiş" style="color:white"> Reddedilmiş Başvurular</a>&nbsp<span class="badge" id="DeniedBadge">  @ViewBag.DeniedCount</span></button>
                </div>
                <div class="col-xs-3" style="width:250px">
                    <div class="input-group" style="width:300px">
                        <div class="input-group-btn">
                            <button type="button" id="filterChoose" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">@Html.DisplayNameFor(model => model.FirstOrDefault().Application.Name)</a></li>
                                <li><a href="#">@Html.DisplayNameFor(model => model.FirstOrDefault().Application.Surname)</a></li>
                                <li><a href="#">@Html.DisplayNameFor(model => model.FirstOrDefault().Application.MobileNumber)</a></li>
                                <li><a href="#">@Html.DisplayNameFor(model => model.FirstOrDefault().Application.IMEINumber)</a></li>
                                <li><a href="#">@Html.DisplayNameFor(model => model.FirstOrDefault().Application.City)</a></li>
                            </ul>
                        </div>
                        <input type="text" class="form-control" placeholder="Aranacak kelimeyi giriniz!" id="filterArea" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <br />

    @foreach (var itemGroup in Model.GroupBy(b => b.ApproveType).OrderBy(o => o.Key))
    {
    var btn = "info";
    var icon = "glyphicon-warning-sign";
    var color = "purple";

    var counter = 1;

    if (itemGroup.Key == "Onaylanmış")
    {
    btn = "success";
    icon = "glyphicon-ok";
    color = "green";
    }
    if (itemGroup.Key == "Reddedilmiş")
    {
    btn = "danger";
    icon = "glyphicon-remove";
    color = "red";
    }

    <div class="panel-@btn">
        <div class="panel-heading" id="panel-@btn" data-toggle="collapse" data-target="#@btn" aria-expanded="true">
            <span class="glyphicon @icon"></span><button type="button" class="btn btn-@btn" id="@itemGroup.Key">
                @itemGroup.Key <span class="badge" id="@btn-badge"> @itemGroup.Count()</span>
            </button>
        </div>
        <table class="table table-striped table-bordered collapse" id="@btn" style="color:@color table-layout:fixed;">
            <tr>
                <th>
                    Sıra
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Application.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Application.Surname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Application.MobileNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Application.IMEINumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Application.Image)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Application.City)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Application.IsApproved)
                </th>
                <th></th>
            </tr>

            @foreach (var item in itemGroup)
            {
            <tbody id="tbody">
                <tr>
                    <td>
                        @counter
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Application.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Application.Surname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Application.MobileNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Application.IMEINumber)
                    </td>
                    <td>
                        <img src="@item.Image" width="100px" height="100px" alt="" />
                        @*@Html.DisplayFor(modelItem => item.Image)*@
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Application.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Application.IsApproved)
                    </td>
                    <td>
                        <div class="btn btn-@btn"><a href=@Url.Action("ApplicationDetails", "Samsung" , new { ID=item.Application.ID }) style="color:white;text-decoration:none">Detayları Görüntüle</a></div>
                        @*@Html.ActionLink("Detayları Görüntüle", "ApplicationDetails", new { ID = item.Application.ID })*@
                    </td>
                </tr>
            </tbody>
            counter++;
            }
        </table>
    </div>
    <hr />
    }